name: Auto Assign PR Author and Reviewers

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign assignee and reviewers
        uses: kentaro-m/auto-assign-action@v2.0.1
        with:
          configuration-path: .github/auto_assign.yml
